[2023-06-21 13:35:29 +0000] [24993] [INFO] Starting gunicorn 20.1.0
[2023-06-21 13:35:29 +0000] [24993] [INFO] Listening at: http://0.0.0.0:3000 (24993)
[2023-06-21 13:35:29 +0000] [24993] [INFO] Using worker: sync
[2023-06-21 13:35:29 +0000] [24994] [INFO] Booting worker with pid: 24994
[2023-06-21 13:35:29 +0000] [24994] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'task1'
[2023-06-21 13:35:29 +0000] [24994] [INFO] Worker exiting (pid: 24994)
[2023-06-21 13:35:29 +0000] [24993] [INFO] Shutting down: Master
[2023-06-21 13:35:29 +0000] [24993] [INFO] Reason: Worker failed to boot.
[2023-06-21 13:37:34 +0000] [25005] [INFO] Starting gunicorn 20.1.0
[2023-06-21 13:37:34 +0000] [25005] [INFO] Listening at: http://0.0.0.0:3000 (25005)
[2023-06-21 13:37:34 +0000] [25005] [INFO] Using worker: sync
[2023-06-21 13:37:34 +0000] [25006] [INFO] Booting worker with pid: 25006
[2023-06-21 13:37:34 +0000] [25006] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'task1'
[2023-06-21 13:37:34 +0000] [25006] [INFO] Worker exiting (pid: 25006)
[2023-06-21 13:37:34 +0000] [25005] [INFO] Shutting down: Master
[2023-06-21 13:37:34 +0000] [25005] [INFO] Reason: Worker failed to boot.
[2023-06-21 13:37:48 +0000] [25008] [INFO] Starting gunicorn 20.1.0
[2023-06-21 13:37:48 +0000] [25008] [INFO] Listening at: http://0.0.0.0:3000 (25008)
[2023-06-21 13:37:48 +0000] [25008] [INFO] Using worker: sync
[2023-06-21 13:37:48 +0000] [25009] [INFO] Booting worker with pid: 25009
[2023-06-21 13:37:48 +0000] [25009] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'task1'
[2023-06-21 13:37:48 +0000] [25009] [INFO] Worker exiting (pid: 25009)
[2023-06-21 13:37:48 +0000] [25008] [INFO] Shutting down: Master
[2023-06-21 13:37:48 +0000] [25008] [INFO] Reason: Worker failed to boot.
[2023-06-21 13:38:01 +0000] [25024] [INFO] Starting gunicorn 20.1.0
[2023-06-21 13:38:01 +0000] [25024] [INFO] Listening at: http://0.0.0.0:3000 (25024)
[2023-06-21 13:38:01 +0000] [25024] [INFO] Using worker: sync
[2023-06-21 13:38:01 +0000] [25025] [INFO] Booting worker with pid: 25025
[2023-06-21 13:38:01 +0000] [25025] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'task1'
[2023-06-21 13:38:01 +0000] [25025] [INFO] Worker exiting (pid: 25025)
[2023-06-21 13:38:01 +0000] [25024] [INFO] Shutting down: Master
[2023-06-21 13:38:01 +0000] [25024] [INFO] Reason: Worker failed to boot.
[2023-06-21 13:39:16 +0000] [25033] [INFO] Starting gunicorn 20.1.0
[2023-06-21 13:39:16 +0000] [25033] [INFO] Listening at: http://0.0.0.0:3000 (25033)
[2023-06-21 13:39:16 +0000] [25033] [INFO] Using worker: sync
[2023-06-21 13:39:16 +0000] [25034] [INFO] Booting worker with pid: 25034
[2023-06-21 13:39:16 +0000] [25034] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'task1'
[2023-06-21 13:39:16 +0000] [25034] [INFO] Worker exiting (pid: 25034)
[2023-06-21 13:39:16 +0000] [25033] [INFO] Shutting down: Master
[2023-06-21 13:39:16 +0000] [25033] [INFO] Reason: Worker failed to boot.
[2023-06-21 14:44:05 +0000] [25786] [INFO] Starting gunicorn 20.1.0
[2023-06-21 14:44:05 +0000] [25786] [INFO] Listening at: http://0.0.0.0:3000 (25786)
[2023-06-21 14:44:05 +0000] [25786] [INFO] Using worker: sync
[2023-06-21 14:44:05 +0000] [25787] [INFO] Booting worker with pid: 25787
[2023-06-21 14:44:05 +0000] [25787] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'task1'
[2023-06-21 14:44:05 +0000] [25787] [INFO] Worker exiting (pid: 25787)
[2023-06-21 14:44:05 +0000] [25786] [INFO] Shutting down: Master
[2023-06-21 14:44:05 +0000] [25786] [INFO] Reason: Worker failed to boot.
